### ISSUE TITLE
Wrong form control validation

### ISSUE THREAD

**Issue by Eugeno** [JsDaddy/ngx-mask#746]
**Version `9.0.2`**

conditions:
```
prefix: '+7',
mask: '000 000-00-00',
```

✔ first results:
```
errors:
  mask:
    actualValue: "+7 111 11"
    requiredMask: "000 000-00-00"
status: "INVALID"
value: "+7 111 11"
```

❌ after **6** symbols:
```
errors: null
status: "VALID"
value: "+7 111 111"
```

Without prefix (mask `000 000-00-00`) it works correctly before **8** symbols (wrong `errors: null` at `111 111-11`).

❕ **There is no such problem at `8.2.0`**
